name: AmongUs
version: 0.1
main: one.jgr.amongUs.main.Main
authors: [Lars Jaeger, JAB_1305]
depend: [WorldEdit,WorldGuard]
description: AmongUs for Minecraft
api-version: 1.15
commands:
  amongus:
    description: controls the game
    aliases: [au]